Repository nickmaglowsch/mention_bot_telegram, pull requests merged in 2023-02, with the labels that each got.

#12 Enhance/add eslint config
  .eslintrc.json
  .gitignore
  package.json
  src/commands/add.test.ts
  src/commands/add.ts
  src/commands/create.test.ts
  src/commands/create.ts
  src/commands/mention.test.ts
  src/commands/mention.ts
  src/factory.test.ts
  src/factory.ts
  src/index.ts
  src/interfaces/commandArgs.ts
  src/interfaces/commands.ts
  src/models/group.ts
  src/utils.test.ts
  src/utils.ts
Labels: enhancement

#14 feat: add delete command
  package.json
  src/commands/create.test.ts
  src/commands/delete.test.ts
  src/commands/delete.ts
  src/factory.test.ts
  src/factory.ts
  src/interfaces/commands.ts
Labels: feature

#19 Add command to leave a group
  .eslintrc.json
  .prettierrc
  package.json
  src/commands/add.ts
  src/commands/leave.test.ts
  src/commands/leave.ts
  src/factory.test.ts
  src/factory.ts
  src/index.ts
  src/interfaces/commandArgs.ts
  src/interfaces/commands.ts
  src/mocks/factory.mock.ts
  src/mocks/leave.mock.ts
Labels: feature, new command

#21 Fix/leave command
  .gitignore
  src/commands/leave.test.ts
  src/commands/leave.ts
  src/mocks/leave.mock.ts
Labels: bugfix

#22 fix: remove error message for when group does not exists
  src/commands/mention.test.ts
  src/commands/mention.ts
  src/index.ts
Labels: bugfix

#24 Doc: created README.md
  README.md
  package.json
Labels: documentation

#23 Feat: remove command
  src/commands/remove.test.ts
  src/commands/remove.ts
  src/factory.test.ts
  src/factory.ts
  src/interfaces/commands.ts
  src/mocks/factory.mock.ts
Labels: feature

#25 Feat: help command
  src/commands/help.test.ts
  src/commands/help.ts
  src/factory.test.ts
  src/factory.ts
  src/interfaces/commands.ts
  src/utils.test.ts
  src/utils.ts
Labels: feature

#28 factory refactor
  src/commands/add.test.ts
  src/commands/add.ts
  src/commands/create.test.ts
  src/commands/create.ts
  src/commands/delete.test.ts
  src/commands/delete.ts
  src/commands/help.test.ts
  src/commands/help.ts
  src/commands/index.test.ts
  src/commands/index.ts
  src/commands/leave.test.ts
  src/commands/leave.ts
  src/commands/mention.test.ts
  src/commands/mention.ts
  src/commands/remove.test.ts
  src/commands/remove.ts
  src/factory.test.ts
  src/factory.ts
  src/index.ts
  src/interfaces/commandArgs.ts
  src/interfaces/commands.test.ts
  src/interfaces/commands.ts
  src/utils.test.ts
  src/utils.ts
Labels: refactor

#29 feat: List all groups in a server
  src/commands/index.ts
  src/commands/list.test.ts
  src/commands/list.ts
  src/interfaces/commands.ts
Labels: feature

#32 Fix: mentions not working with ~
  src/factory.test.ts
  src/factory.ts
Labels: bugfix
